export const QUERY_KEYS = {
  POST_KAKAO: ['POST_KAKAO'],
  POST_JOIN: ['POST_JOIN'],
  GET_GROOMER_ESTIMATE_LIST: ['GET_GROOMER_ESTIMATE_LIST'],
  GET_GROOMER_ESTIMATE_DETAIL: ['GET_GROOMER_ESTIMATE_DETAIL'],

  POST_GROOMER_ESTIMATE: ['POST_GROOMER_ESTIMATE_DETAIL'],
} as const;
