const AUTH_QUERY_KEYS = {
  POST_KAKAO: ['POST_KAKAO'],
  POST_VET_JOIN: ['POST_VET_JOIN'],
};

const ESTIMATE_QUERY_KEYS = {};

const NOTIFICATION_QUERY_KEYS = {
  GET_VET_SCHEDULE: ['GET_VET_SCHEDULE'],
};

export const QUERY_KEYS = {
  ...AUTH_QUERY_KEYS,
  ...ESTIMATE_QUERY_KEYS,
  ...NOTIFICATION_QUERY_KEYS,
};
