export const QUERY_KEYS = {
  POST_KAKAO: ['POST_KAKAO'],
  POST_KAKAO_OAUTH: ['POST_KAKAO_OAUTH'],
  POST_OAUTH_KAKAO: ['POST_OAUTH_KAKAO'],
  POST_JOIN_WITHOUT_PET: ['POST_JOIN_WITHOUT_PET'],
  POST_AVAILABLE_NICKNAME: ['POST_AVAILABLE_NICKNAME'],
  GET_BREED_LIST: ['GET_BREED_LIST'],
  POST_JOIN_WITH_PET: ['POST_JOIN_WITH_PET'],
  GET_DAENGLE_ESTIMATE_LIST: ['GET_DAENGLE_ESTIMATE_LIST'],

  GET_USER_GROOMING_MY_REVIEW_LIST: ['GET_USER_GROOMING_MY_REVIEW_LIST'],
  GET_USER_CARE_MY_REVIEW_LIST: ['GET_USER_CARE_MY_REVIEW_LIST'],

  DELETE_USER_CARE_REVIEW: ['DELETE_USER_CARE_REVIEW'],
  DELETE_USER_GROOMING_REVIEW: ['DELETE_USER_GROOMING_REVIEW'],
} as const;
