export const QUERY_KEYS = {
  POST_KAKAO: ['POST_KAKAO'],
  POST_KAKAO_OAUTH: ['POST_KAKAO_OAUTH'],
  POST_OAUTH_KAKAO: ['POST_OAUTH_KAKAO'],
  POST_JOIN_WITHOUT_PET: ['POST_JOIN_WITHOUT_PET'],
  POST_AVAILABLE_NICKNAME: ['POST_AVAILABLE_NICKNAME'],
  GET_BREED_LIST: ['GET_BREED_LIST'],
  POST_JOIN_WITH_PET: ['POST_JOIN_WITH_PET'],
<<<<<<< HEAD
} as const;
=======
  GET_DAENGLE_ESTIMATE_GROOMER_DETAIL: ['GET_DAENGLE_ESTIMATE_GROOMER_DETAIL'],
  GET_DAENGLE_ESTIMATE_VET_DETAIL: ['GET_DAENGLE_ESTIMATE_VET_DETAIL'],
};
>>>>>>> 0b8b62b (refactor(daengle): 쿼리 폴더 구조 수정)
